### PR TITLE
Add documentation to illustrate commands

### PR DESCRIPTION
**Pull request by jcaw**
Fix for issue:
https://github.com/abingham/emacs-traad/issues/20

Issue: "Functions need more documentation in relationship with Rope"

Add more documentation to user-facing commands, including short explanations and
examples for refactorings. Should make the outcome of individual Traad commands
clearer.

### CODE REVIEW

**Comment by abingham** [comment]
This is wonderful, thank you! My only issue is the use of `>>>` before the Python code examples. My eyes immediately though "REPL" when I saw them, though of course they don't indicate that at all. Are line-leaders like that necessary? Could we just remove them? I don't think we'd lose any explanatory power by doing so.

**Comment by jcaw** [comment]
I thought about that too, happy to remove them. How about 4-spaced indentation?

**Comment by abingham** [comment]
I think that will work great. If we decide later that we don't like it, we
can change it then. Thanks again!

**Comment by jcaw** [comment]
I tried out spaced indentation, plus the " | " character as a line leader. Added a commit for both versions. I think " | " is a bit clearer (it helps to visually segregate the code) but you might prefer spaces.

**Comment by abingham** [comment]
Looks great, thanks!

**Pull request merged**
